---
frontend:
  transport: "tcp"
  host: "0.0.0.0"
  port: 5550
  bind: True
  highwatermark: 5

backend:
  transport: "ipc"
  host: localhost
  port: 5551
  bind: True

backend_other:
  transport: "ipc"
  host: localhost
  port: 5552
  bind: True

broker:
  type: lb_with_xsub_extra_xpub
  io_threads: 3

verbose: True
debug: False