---
frontend:
  transport: "ipc"
  host: localhost
  port: 5553
  bind: True

backend:
  transport: "ipc"
  host: localhost
  port: 5554
  bind: True

model: BasicRazTracker

verbose: True
debug: False