---
type: "camera"
sensor_class: "ReplayCamera"
dataset: "nuScenes"
data_dir: "./data/nuScenes"
split: "v1.0-mini"
scene: "scene-0103"
serial: Null
width: 1600
height: 900
fps: 2
jpg_compression_pct: 80
interpolate: Null
io_threads: 2
calibration:
  channel_order: "rgb"  # after flipping order in image loading
  intrinsics:
    fx: 1252.81310
    fy: 1252.81310
    u: 826.588115
    v: 469.984663
    g: 0
  extrinsics:
    dx: 0
    dy: 0
    dz: 0
    qx: 0
    qy: 0
    qz: 0
backend:
  transport: "ipc"
  host: "localhost"
  port: 5550
  bind: False
verbose: True
debug: False