---
modules:
  broker:
    config: "broker/default.yml"
  detection:
    config: "detection/jetson_camera.yml"
  tracking:
    config: "tracking/camera.yml"
  display:
    config: "display/default.yml"